[package]
name = "archaeologus-git"
version.workspace = true
edition.workspace = true

[dependencies]
archaeologus-core = { workspace = true }
git2 = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3"
criterion = { workspace = true }

[[bench]]
name = "git_bench"
harness = false

[lints]
workspace = true
