[package]
name = "archaeologus-db"
version.workspace = true
edition.workspace = true

[dependencies]
archaeologus-core = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }

[lints]
workspace = true
